import Head from "next/head";

export async function getServerSideProps({ res }) {
  res.writeHead(302, {
    Location: "/planets/mercury",
  });
  res.end();
}

export default function Home() {
  // return (
  //   <>
  //     <Head>
  //       <title>Planet Factopia</title>
  //       <meta name="description" content="Generated by create next app" />
  //       <meta name="viewport" content="width=device-width, initial-scale=1" />
  //       {/* <link rel="icon" href="/favicon.ico" /> */}
  //     </Head>
  //     {/* <PlanetInfo /> */}
  //   </>
  // );
  return null;
}
